name: CI/CD
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: "yarn"
      - run: yarn
      - run: yarn build
      - uses: EndBug/add-and-commit@v9.0.0
        with:
          author: ${{ github.actor }}
          mesage: "CI/CD: commit"
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
